//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeapingGorilla.SecretStore.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeapingGorilla.SecretStore.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;yFjSLZrefqfTLlj6LDH0U8OGu+s8TxPjs1qJauCaD6KSkNXORZtZ6+0McH8C/faubUkfdW3SQEixd9vuAabC0P/25ba/wbnrXCfcc5xMgOLD1E/SOo0hn5AkmYTsj2lqpmoAal8mUCWsPcAD8ibUaCdhpbkoDEBP0iNCDmZupL8=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;6T22vXZkQ2bCdUzji47ZruiBJ8XEAfUdJQ/tR+TOZZgaisEFDRyt+Tt22Vtrk67W+5IgUl6wZsPq7An0rggwBw==&lt;/P&gt;&lt;Q&gt;2+VsRSxSWQihSp8j6fFBEc7Bnl6GlTYj0b0Yqyk6nGTu8f5P/QmAziGijWj/iwn1JgSBCBw8R+7tRXx0pq1HiQ==&lt;/Q&gt;&lt;DP&gt;wk50X3Ay5OfFlj0Az3GpLYpqlnyt5seRiR+0mBEoVQCbE/7rO1oqIRiF0VvUygp89MVugdB6epI6sns0yIrvnw==&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestRsaKey {
            get {
                return ResourceManager.GetString("TestRsaKey", resourceCulture);
            }
        }
    }
}
