//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeapingGorilla.SecretStore.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeapingGorilla.SecretStore.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;
        ///	&lt;Modulus&gt;rJpxBNWDUDK9ilSyOcxzCmcBHMLKxPJAb0TK+odiU4x1nJWaUz6RrCj//zyFLnoNl7Xl2fF1FgIZOb8x0x8ny95VDRh5TX10g1uztmg6dsMR0e2Uew1K3ZbwgAKFsGVg1FynYSVQbueIGFkDaDNLHJcGxw8mogBJ9YrFj/6OExXPUFlYRaFCvHmpUSRlGT5Oq01/IaaTiAF6FsIxoupwQdEza0P/ihv60ZxCx8gAwa1tJ/tY/+RdBP+4I5kz0twEPY9Qd2wsPLHpquyG/COWHZNGet2BWd1x+ALOCSQfjJE491Cn+S1BXKGZMD2tz9raGEbiGBkLJLW0EpT5Jhx4FoECt0bOOu+viRTZ60tk+P8n60DnC2KlnomFmagKdNi43fTc+rLzE9sMnlXhMFtW9nKTJ8epDb0mCi5Y603dfwdQqK8xbwmBAE3srpwdJFj1og9f56ADGtGZirwTSuPbnSXmhQIJA1Vb85U7ZZv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestRsaKey {
            get {
                return ResourceManager.GetString("TestRsaKey", resourceCulture);
            }
        }
    }
}
