version: '3.8'
services:
  postgres:
    image: postgres:14.2
    ports:
      - "54340:5432"
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/init-database.sh
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: plaything-osmosis-calzone-reiterate-pesticide-hazelnut